### ISSUE TITLE
InvalidFormat BusinessClassification 

### ISSUE THREAD

**Issue by alexgnatrow** [Dwolla/v2-ach-api-docs#128]
I already triple-checked this.

I'm  trying to implement user creation with type: business and the only thing why dwolla response is crashing is this:  
<pre> {
"code":"ValidationError",
"message":"Validation error(s) present. See embedded errors list for more details.",
"_embedded":{
"errors":[{
"code":"InvalidFormat",
"message":"BusinessClassification invalid.",
"path":"/businessClassification",
"_links":{}
}]}}
</pre>

And again. I checked that this businessClassification is EXACTLY the same format as in the docs, because I just retreive the array, user pick one and i just send id to the server.

<details>
<summary>logs</summary>
<pre> backend Dwolla api error {
"code":"ValidationError",
"message":"Validation error(s) present. See embedded errors list for more details.",
"_embedded":{
"errors":[{
"code":"InvalidFormat",
"message":"BusinessClassification invalid.",
"path":"/businessClassification",
"_links":{}
}]}}
.
.

The object I am sending to dwolla 
{
Type: {Type: "Sole Proprietorship"},
address: {
Address1: "some address 1", 
Address2: null, 
city: "dfgdfg", 
stateName: "NY", 
zip: "12312"},
businessClassification: "9ed3a866-7d6f-11e3-a0ce-5404a6144203",
businessName: "qwertyuiop",
businessUsername: "qwepui",
dob: "1980-10-19",
email: "asdagfplok@asdasd.com",
firstName: "asdfghjkl",
lastName: "asdfghjkl",
password: "123456780",
ssn: "1123",
}
</pre>
</details>

**Comment by spencerhunter** [comment]
Hi @alexgnatrow , We'll work on updating the documentation for clarification. When creating the customer you’ll want to pass in an industry classification Id. The business classifications list will return business classifications with an `_embedded` list of industry classifications. You’ll need the industry classification id and not a business classification id. For example, 9ed3a866-7d6f-11e3-a0ce-5404a6144203 is the Business Classification for Entertainment and media, you'll want to pass in something like 9ed3cf56-7d6f-11e3-ba87-5404a6144203, which corresponds to Concert tickets.

**Comment by alexgnatrow** [comment]
Ok my issue is resolved. 
A little bit unexpected but I should just explore the data I received, I think. 
Thanks for the help anyway!
