### ISSUE TITLE
dwolla server error when trying to update just created user

### ISSUE THREAD

**Issue by alexgnatrow** [Dwolla/v2-ach-api-docs#131]
Some weird error received when I create account with minimal needed, retreive the id and trying to update it to verified user.

<details>
<summary>here is the code</summary>
<pre>Dwolla server error {
"code":"ServerError",
"message":"A server error occurred. Error ID: 4879c3aa-7e02-476e-9141-14c494fa5d57."
}</pre>
</details>

**Comment by spencerhunter** [comment]
Hey @alexgnatrow , are you able to reply back with the raw request body that resulted in this error?

**Comment by alexgnatrow** [comment]
dwolla update body { firstName: 'Account',
  lastName: 'Admin',
  email: 'accountAdmin@email.com',
  address1: '99-99 33rd St',
  city: 'Some City',
  state: 'NY',
  controller: 
   { firstName: 'John',
     lastName: 'Controller',
     title: 'CEO',
     dateOfBirth: '1980-01-31',
     ssn: '1234',
     address: 
      { address1: '1749 18th st',
        address2: 'apt 12',
        city: 'Des Moines',
        stateProvinceRegion: 'IA',
        postalCode: '50266',
        country: 'US',
        password: 'somepassword' } },
  businessClassification: '9ed3f670-7d6f-11e3-b1ce-5404a6144203',
  businessName: 'Jane Corp',
  ein: '00-0000000' }
