### ISSUE TITLE
Strange date of birth validation error validation error 

### ISSUE THREAD

**Issue by alexgnatrow** [Dwolla/v2-ach-api-docs#135]
Strange date of birth validation error validation error occur, look at the screenshots from output and docs below.

<details>
<summary>create input</summary>
<pre><code>
{
 firstName: 'lancelot',
  lastName: 'tauriel',
  email: 'vaaaao23456789lor+personal+test1542209567562@valiant.com' 
}
</code></pre>
</details>

<details>
<summary>update input</summary>
<pre><code>
{ 
firstName: 'lancelot',
  lastName: 'tauriel',
  email: 'vaaaao23456789lor+personal+test1542209571392@valiant.com',
  type: 'personal',
  address1: '99-99 33rd St',
  city: 'Some City',
  state: 'NY',
  postalCode: '89798',
  dateOfBirth: '2018-11-13',
  ssn: '1234'
 }
</code></pre>
</details>

<details>
<summary>docs</summary>
<pre><code>
var requestBody = {
  firstName: 'John',
  lastName: 'Doe',
  email: 'jdoe@nomail.net',
  type: 'personal',
  address1: '99-99 33rd St',
  city: 'Some City',
  state: 'NY',
  postalCode: '11101',
  dateOfBirth: '1970-01-01',
  // For the first attempt, only the
  // last 4 digits of SSN required
  // If the entire SSN is provided,
  // it will still be accepted
  ssn: '1234'
};
</code></pre>
</details>

<details>
<summary>output</summary>
<pre>
Could not write dwolla account id ValidationError: DateOfBirth value not allowed.

</pre>
</details>

As you can see I receive date of birth validation error when I should not.
Or am I missing something?

**Comment by CoolStoryCory** [comment]
Hello @alexgnatrow, we do validation to make sure your Customer is at least 18 years old. 
It looks like you were trying to pass the value of `2018-11-13` as the DateOfBirth. 
Perhaps trying something like `1995-11-13`.

Let me know how it goes!

**Comment by alexgnatrow** [comment]
Yeah. Dramatically simple mistake to make, sorry. 
Thanks for your time!
