### ISSUE TITLE
Beneficial owner document with documentType = other?

### ISSUE THREAD

**Issue by abevoelker** [Dwolla/v2-ach-api-docs#158]
The API docs for creating beneficial owner documents mention `other` as a possible value: https://github.com/Dwolla/v2-ach-api-docs/blob/79816664b4b6093d5350c3a6aea57c47310c403f/source/includes/_documents.md#create-a-document-for-a-beneficial-owner

But the business verified customer walkthrough only mentions `license`, `idCard`, and `passport`: https://developers.dwolla.com/resources/business-verified-customer/adding-beneficial-owners.html#determining-verification-documents-needed

I assume `other` doesn't really make sense for a beneficial owner document - only Customers?

**Comment by ShreyaThapa** [comment]
Hi @abevoelker, thanks for pointing this out! A document _can_ be uploaded with type `other` for Beneificial Owners. We will update the business verified customer walkthrough resource article to include `other` as a document type.
