### ISSUE TITLE
Remove Funding Source Raw example is incorrect

### ISSUE THREAD

**Issue by bnjmn** [Dwolla/v2-ach-api-docs#40]
The v2 documentation for [Removing a Funding Source](https://docsv2.dwolla.com/#remove-a-funding-source) shows an example of a `RAW` request and response for `POST /transfers` not `DELETE /funding-sources/...`. The other examples for this endpoint seem to be correct.

**Comment by spencerhunter** [comment]
This should now be fixed. Thanks for pointing this out!
