### ISSUE TITLE
Fix typo in raw + php create customer examples

### ISSUE THREAD

**Issue by sausman** [Dwolla/v2-ach-api-docs#65]
https://developers.dwolla.com/guides/transfer-money-between-users/create-verified-customer.html 

- [x] Raw and PHP examples have `address` instead of `address1`
- [x] Underscores

**Comment by cpiggott** [comment]
Documentation of property accessors for objects in PHP are currently labeled as 
```$customer->firstName```
The documentation for a majority of the properties in the PHP API docs use lowerCamelCase in examples. [Retrieve A Customer](https://docsv2.dwolla.com/#retrieve-a-customer)

After retrieving a Customer from the API and doing a variable dump, the properties are in underscore_notation. 

```
{
  "_links": {
    "self": {
    },
    "receive": {
    },
    "edit-form": {
    },
    "edit": {
    },
    "funding-sources": {
    },
    "transfers": {
    },
    "send": {
    }
  },
  "_embedded": null,
  "id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "first_name": "First",
  "last_name": "Last",
  "email": "email@email.com",
  "type": "business",
  "status": "verified",
  "created": "2017-06-15T20:13:43.460Z",
  "address1": "99-99 33rd St",
  "address2": null,
  "city": "Some City",
  "state": "NY",
  "postal_code": "11101",
  "phone": null,
  "business_name": "Jane Corp",
  "doing_business_as": null,
  "website": null
}
```
